### ISSUE TITLE
Change Main Controller on demand.

### ISSUE THREAD

**Issue by jturolla** [shahzin/SKSlideViewController#5]
Is this possible? I coudn't find a way.

**Comment by shahzin** [comment]
You can use any of the public methods

StoryBoard IDs

```
-(void)setStoryBoardIDForMainController:(NSString *)mainControllerID
                     leftController:(NSString *)leftControllerID
                    rightController:(NSString *)rightControllerID;
```

Segue IDs

```
-(void)setSegueIDForMainController:(NSString *)mainControllerID
                leftController:(NSString *)leftControllerID
               rightController:(NSString *)rightControllerID;
```

ViewControllers

```
-(void)setSlideViewControllerUsingMainViewController:(UIViewController<SKSlideViewDelegate> *)mainController
                              leftViewController:(UIViewController<SKSlideViewDelegate> *)leftViewController
                             rightViewController:(UIViewController<SKSlideViewDelegate> *)rightController;
```

And then you could call the public method

```
-(void)reloadControllers;
```

hope this helps.

**Comment by jturolla** [comment]
I'm sorry, I thought this could only be done before the view was showing/at the prepare for segue.

**Comment by shahzin** [comment]
I hope this issue is solved. :) let me know any feedback you have and suggestions if you think that the above method is insufficient.

**Comment by jturolla** [comment]
Well, what I'm trying to do is to change the MainVC from a button on the LeftVC. Unfortunately when I call the  

```
[self.slideViewController setStoryBoardIDForMainController:@"AlternateMainVC" leftController:@"LeftVC" rightController:nil];
[self.slideViewController reloadControllers];
```

Methods, the VC get unloaded, but they don't reload, and the background of the SlideVC appears on the screen. 

For my use case, I need to change only the MainVC, keeping the LeftVC loaded, and it's not working the way you told me it would, unfortunetelly.

**Comment by shahzin** [comment]
I  will work on this issue. 

Meanwhile I have a suggestion for you . If you change your main view controller too often, Make the MainVC as a place holder and Use View controller containment to change the view controller based on the messages from LeftVC .

**Comment by jturolla** [comment]
That was my idea too, thanks.
